export const SET_USER_SEARCH_RESULT = "SET_USER_SEARCH_RESULT";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_EDIT_GROUP_MODEL_STATE = "SET_MODEL_STATE";
export const SET_EDIT_GROUP_NAME_TO_MEMBER_STATE = "SET_EDIT_GROUP_NAME_TO_MEMBER_STATE";
export const SET_PARTICIPANT_MODEL_STATE = "SET_PARTICIPANT_MODEL_STATE";
export const SET_QUOTE = "SET_QUOTE";
export const SET_SEEN = "SET_SEEN";
export const SET_NIGHT_MODE = "SET_NIGHT_MODE";
