export const SET_ACTIVE_USER = "SET_ACTIVE_USER";
export const SET_ACTIVE_GROUP = "SET_ACTIVE_GROUP";
export const SET_CONTACT_USERS = "SET_CONTACT_USERS";
export const SET_USER_GROUPS = "SET__USER_GROUPS";
export const SET_GROUP_MEM_INFO = "SET__GROUP_MEM_INFO";
export const SET_IS_TYPING = "SET_IS_TYPING";
export const SET_NEW_GROUP_MESSAGE = "SET_NEW_GROUP_MESSAGE";