export const SET_USER_MESSAGES = "SET_USER_MESSAGES";
export const SET_GROUP_MESSAGES = "SET_GROUP_MESSAGES"
export const ADD_TEMP_MESSAGES = "ADD_TEMP_MESSAGES";
export const DELETE_TYPED_MSG = "DELETE_TYPED_MSG";
export const SET_CONTACTS_TOTAL = "SET_CONTACTS_TOTAL";